### ISSUE TITLE
Incompatible with PhpStorm 2021.3 Beta

### ISSUE THREAD

**Issue by kdambekalns** [cvette/intellij-neos#100]
The release of PhpStorm 2021.3 is coming nearer, and it would be so much awesome to have this plugin working with it…

<img width="454" alt="image" src="https://user-images.githubusercontent.com/95873/141651674-80dbc998-d215-4b56-9215-cdc0a7f354ba.png">

**Comment by cvette** [comment]
Fixed with version 1.12

**Comment by kdambekalns** [comment]
Yes, I noticed. Thanks a bunch! 🚀
