### ISSUE TITLE
Reformat Code has problem with direct use of property attribute

### ISSUE THREAD

**Issue by mad99** [cvette/intellij-neos#12]
Cool Plugin at all!
Thank you for the great tool.

Maybe is some build-in from phpStorm and not connected to your Plugin.
Use of direct property-attribute like in 
data-width = ${q(node).property('image').width} 
produce problem for phpStom-Function «Code > Reformat Code». The auto-indenting will collapse the code below this line. Maybe it decrypt it as a code-error. But isn't!

Right Code-Indenting «by Hand»
![right-indenting-byhand](https://cloud.githubusercontent.com/assets/6169308/25217040/a56be4c4-25a5-11e7-86ed-f29d92224a93.png)

Wrong Code-Indenting «by Code > Reformat Code»
![wrong-indenting-by-reformatcode](https://cloud.githubusercontent.com/assets/6169308/25217060/c0febaa4-25a5-11e7-8bbc-34ba6fd78384.png)

Popup when hover over wafy-line: «EEL_FUNCTION expected, got 'width'»
When I delete this line, the same behavior with line 63. Also collapse all following lines.
The code as itself works fine in Neos. So obviously there is a misinterpreting from phpStorm or Plugin.

**Comment by cvette** [comment]
@mad99 Are you using the lastest version of the plugin (0.1.12) ? I fixed this issue yesterday and it should work properly now.

**Comment by mad99** [comment]
Perfect! (Answer: No I worked on 0.1.11 > sorry) Now indenting is fine!
