### ISSUE TITLE
context-right-click -> New > «TypoScript2» name change to «Fusion»

### ISSUE THREAD

**Issue by mad99** [cvette/intellij-neos#14]
Can't say if the Right-Click Context-Menu in File-Browser (Project) is generated from intellij-neos. 
If it would be, could be less tricky for developer to get the "new" and more Neos-Conform Name for Files: «Fusion».
Until now, I used always the First Line «File». I thought, the TypScript2 Line would create a *.ts2 File. But the courageous (only because the icon was the new one  ;o)) trial today, created a proper *.fusion File.
Would be less dangerous :-O with «Fusion» as name.

![bildschirmfoto 2017-04-28 um 15 20 52](https://cloud.githubusercontent.com/assets/6169308/25530657/5609c152-2c27-11e7-8566-f8b92bf9d74e.png)

**Comment by cvette** [comment]
I think the file template has been added by another plugin. The icon is then automatically assigned via the file extension.
