### ISSUE TITLE
Spaces around operators required incorrectly

### ISSUE THREAD

**Issue by kdambekalns** [cvette/intellij-neos#15]
Expressions like `${"level-"+(q(node).property('_depth')-2)}` or `${'col-sm-' + String.split(q(node).parent().property('layout'), '-')[multiColumnIteration.index]}` get marked as wrong.

The first can be "fixed" by writing it using spaces around the `-` operator (`${"level-"+(q(node).property('_depth') - 2)}`. The second cannot be written differently.

In either case, the syntax is correct, so the plugin should support that.

<img width="1405" alt="array-access-support-missing" src="https://cloud.githubusercontent.com/assets/95873/26096786/a63b53a8-3a22-11e7-92fd-0721d6b80c2b.png">

**Comment by cvette** [comment]
Should be fixed in version 0.1.13

**Comment by kdambekalns** [comment]
Awesome, works like a charm. Thanks!
