### ISSUE TITLE
Fusion AFX: Support for escaped attribute names

### ISSUE THREAD

**Issue by lorenzulrich** [cvette/intellij-neos#153]
Neos 7.3 implemented the ability to use escaped attribute names, e.g. to use AlpineJS as seen below:

![image](https://user-images.githubusercontent.com/1816023/175834593-18577cdd-4d29-4c7a-90e1-88861468b4b2.png)

This syntax is not yet recognized by the Neos Plugin. It would be nice if it was.

**Comment by cvette** [comment]
This is going to be a tough one, since it's invalid HTML. Not sure how to implement this right now.

**Comment by cvette** [comment]
Well, I stand corrected. This was fairly easy. Resolved with 688a60e

**Comment by lorenzulrich** [comment]
Wow, that's great. Thanks a lot!
