### ISSUE TITLE
Change afx attribute "type" autocompletion behavoir

### ISSUE THREAD

**Issue by manuelmeister** [cvette/intellij-neos#175]
Thank you for this awesome plugin!

I have the problem / annoyance that in afx it autocompletes `{}` after I type `attribute=`.
The problem is, that often I don't want braces (`{}`) but just quotes (`""`). 

https://user-images.githubusercontent.com/3001985/199209899-f1656306-c5a7-457e-bd73-8acc749f5c5e.mp4

"My" problem could be solved two different ways:
1. Remove the closing brace `}` if I delete `{`
2. Don't automatically add `{}` after `=`.  Instead:
   - add `={}` if I type `={`
   - add `=""` if I type `="`

**Comment by manuelmeister** [comment]
So cool. Sadly I can't see the afx settings page, as it is disabled? https://github.com/cvette/intellij-neos/commit/1fc01122aad04922d55af58487928cc9bbf69e98

**Comment by cvette** [comment]
It's with the HTML settings:

![2023-06-21_08-43](https://github.com/cvette/intellij-neos/assets/6884391/af471ab2-8dcb-44d4-a720-92b7bcbda619)

**Comment by manuelmeister** [comment]
Thanks! (Could not find it with search)
