### ISSUE TITLE
Highlighting problems with afx an props

### ISSUE THREAD

**Issue by beardcoder** [cvette/intellij-neos#29]
If you use AFX as renderer and you add a space in a string concatenation the highlighting is broken.

![bildschirmfoto 2018-09-10 um 10 06 44](https://user-images.githubusercontent.com/9371658/45284640-574b6400-b4e1-11e8-92d9-69aa26008815.png)

![bildschirmfoto 2018-09-10 um 10 06 37](https://user-images.githubusercontent.com/9371658/45284645-5a465480-b4e1-11e8-8846-79e83129043d.png)

**Comment by cvette** [comment]
This is because we inject the HTML language provided by intellij for AFX. To support special AFX cases, it needs to be implemented as a custom language. #32

**Comment by cvette** [comment]
Should work much better now :)
