### ISSUE TITLE
Keypresses swallowed after update to 1.1.0

### ISSUE THREAD

**Issue by klfman** [cvette/intellij-neos#38]
After Updating to Version 1.1.0 I'm getting the following symptom:

When within the context of

> renderer = afx`
> 
> `

I cannot press enter, backspace or tab keys. The action is swallowed by the IDE.

The same happened to me inside of yaml files. 

For some reason after some random keypresses it sometimes seems to work again for certain keys, but not for others. I have not yet found a way to isolate the problem or deduce a reason why it might happen. But the IDE gives me this [stacktrace](https://github.com/cvette/intellij-neos/files/3476779/stacktrace.txt).

**Version and plugin information:**
IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.98, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: git.explicit.commit.renames.prohibit.multiple.calls=false
Non-Bundled Plugins: Mongo Plugin, org.jetbrains.plugins.rest, BashSupport, com.dmarcotte.handlebars, com.intellij.plugins.html.instantEditing, com.jetbrains.php, me.artspb.idea.php.latest.plugin, vette.neos

**Comment by cvette** [comment]
Should be fixed with version 1.1.1
