### ISSUE TITLE
Index split Settings

### ISSUE THREAD

**Issue by PRGfx** [cvette/intellij-neos#45]
Like `NodeTypes` configurations, `Settings` can be split into `Settings.*.yaml` files. The `DefaultContextFileIndex` should allow for these files as well (`return psiFile.getName().equals("Settings.yaml");`).
However as the base-distribution has `.yaml.example` files, it should probably be checked, whether the filename ends in `.yaml` as well (same might go for the `NodeTypesYamlFileIndex`).

**Comment by cvette** [comment]
Easy to fix, goes in the next release :)
