### ISSUE TITLE
Allow multi-line EEL expressions

### ISSUE THREAD

**Issue by PRGfx** [cvette/intellij-neos#53]
Especially for conditional expressions and callbacks it would be very handy to split long statements into multiple lines.
This (admittedly somewhat constructed) example works in fusion ([fusionpen](https://fusionpen.punkt.de/fusionpen/e90503d9bcbebf63eddd25f59fdb114d142d3779.html)), but breaks the current fusion parser of this plugin and thus highlighting
```js
renderer = ${Array.map(
    [ 1, 2, 3, 4 ],
    x =>
        x % 2 == 0
            ? x * Math.pow(x, 2)
            : x * 2
)}
```

**Comment by cvette** [comment]
This should work now. Formatting will collapse the indentation though.

**Comment by PRGfx** [comment]
Can confirm, thank you.
The formatting is unfortunate but otherwise very helpful for long statements
