### ISSUE TITLE
NodeTypes.schema files are getting indexed

### ISSUE THREAD

**Issue by PRGfx** [cvette/intellij-neos#79]
The NodeType file pattern matches the schema files like these
Packages/Application/Neos.Neos/Resources/Private/Schema/NodeTypes.schema.yaml
Packages/Application/Neos.ContentRepository/Resources/Private/Schema/NodeTypes.schema.yaml

:smile: 
![image](https://user-images.githubusercontent.com/3868790/128538383-a2c4422b-b792-45b7-a854-2cca8bdd8134.png)

Maybe it makes sense to exclude the Schema directory, if that follows a convention. Excluding non Configuration/ directories would exclude testing fixtures as well, which maybe would be useful to have when working there.

**Comment by cvette** [comment]
This should be resolved now, since we are checking for Configuration/NodeType.*.yaml

**Comment by PRGfx** [comment]
Can confirm, thank you :+1:
